version: '3'
services:
  postgres:
    build:
      dockerfile: ./database/Dockerfile
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
